In [1]:
import geopandas as gpd

link="https://github.com/chorrillos/spatial/raw/main/WorldMapDemo.gpkg"
WorldDemo=gpd.read_file(link)

In [19]:
import numpy as np
c = np.array([['b','a','a'],['c','c','a'],['c','b','b'],['a','a','b'],['a','b','c']])

In [20]:
import giddy
m = giddy.markov.Markov(c)

The Markov Chain is irreducible and is composed by:
1 Recurrent class (indices):
[0 1 2]
0 Transient classes.
The Markov Chain has 0 absorbing states.


In [21]:
m.classes


array(['a', 'b', 'c'], dtype='<U1')

In [23]:
print(m.transitions)


[[2. 2. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
